Remote debugging, yeah

diff --git a/.github/workflows/integrate.yaml b/.github/workflows/integrate.yaml
--- a/.github/workflows/integrate.yaml
+++ b/.github/workflows/integrate.yaml
@@ -9,92 +9,92 @@ on:
     - cron: '0 3 3 * *'
 
 jobs:
-  composer-json-lint:
-    name: "Lint composer.json"
-
-    runs-on: "ubuntu-latest"
-
-    strategy:
-      matrix:
-        php-version:
-          - "7.4"
-
-    steps:
-      - name: "Checkout"
-        uses: "actions/checkout@v2"
-
-      - name: "Install PHP"
-        uses: "shivammathur/setup-php@v2"
-        with:
-          coverage: "none"
-          php-version: "${{ matrix.php-version }}"
-          tools: composer:v1, composer-normalize, composer-require-checker, composer-unused
-
-      - name: "Get composer cache directory"
-        id: composercache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-
-      - name: "Cache dependencies"
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composercache.outputs.dir }}
-          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
-          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
-
-      - name: "Install dependencies"
-        run: "composer update --no-interaction --no-progress"
-
-      - name: "Validate composer.json"
-        run: "composer validate --strict"
-
-      - name: "Normalize composer.json"
-        run: "composer-normalize --dry-run"
-
-      - name: "Check composer.json explicit dependencies"
-        run: "composer-require-checker check --config-file=$(realpath composer-require-checker.json)"
-
-      - name: "Check composer.json unused dependencies"
-        run: "composer-unused"
-
-  xml-lint:
-    name: "Lint XMLs"
-
-    runs-on: ubuntu-latest
-
-    strategy:
-      matrix:
-        php-version:
-          - "7.4"
-
-    steps:
-      - name: "Checkout"
-        uses: "actions/checkout@v2"
-
-      - name: "Install PHP"
-        uses: "shivammathur/setup-php@v2"
-        with:
-          coverage: "none"
-          php-version: "${{ matrix.php-version }}"
-          tools: composer:v1
-
-      - name: "Get composer cache directory"
-        id: composercache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-
-      - name: "Cache dependencies"
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composercache.outputs.dir }}
-          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
-          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
-
-      - name: "Install dependencies"
-        run: "composer update --no-interaction --no-progress"
-
-      - name: "Lint XMLs"
-        uses: ./.github/lint-xml-configuration
-        with:
-          args: bash .github/lint-xml-configuration/lint-xml-configuration.sh
+#  composer-json-lint:
+#    name: "Lint composer.json"
+#
+#    runs-on: "ubuntu-latest"
+#
+#    strategy:
+#      matrix:
+#        php-version:
+#          - "7.4"
+#
+#    steps:
+#      - name: "Checkout"
+#        uses: "actions/checkout@v2"
+#
+#      - name: "Install PHP"
+#        uses: "shivammathur/setup-php@v2"
+#        with:
+#          coverage: "none"
+#          php-version: "${{ matrix.php-version }}"
+#          tools: composer:v1, composer-normalize, composer-require-checker, composer-unused
+#
+#      - name: "Get composer cache directory"
+#        id: composercache
+#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+#
+#      - name: "Cache dependencies"
+#        uses: actions/cache@v2
+#        with:
+#          path: ${{ steps.composercache.outputs.dir }}
+#          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
+#          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
+#
+#      - name: "Install dependencies"
+#        run: "composer update --no-interaction --no-progress"
+#
+#      - name: "Validate composer.json"
+#        run: "composer validate --strict"
+#
+#      - name: "Normalize composer.json"
+#        run: "composer-normalize --dry-run"
+#
+#      - name: "Check composer.json explicit dependencies"
+#        run: "composer-require-checker check --config-file=$(realpath composer-require-checker.json)"
+#
+#      - name: "Check composer.json unused dependencies"
+#        run: "composer-unused"
+#
+#  xml-lint:
+#    name: "Lint XMLs"
+#
+#    runs-on: ubuntu-latest
+#
+#    strategy:
+#      matrix:
+#        php-version:
+#          - "7.4"
+#
+#    steps:
+#      - name: "Checkout"
+#        uses: "actions/checkout@v2"
+#
+#      - name: "Install PHP"
+#        uses: "shivammathur/setup-php@v2"
+#        with:
+#          coverage: "none"
+#          php-version: "${{ matrix.php-version }}"
+#          tools: composer:v1
+#
+#      - name: "Get composer cache directory"
+#        id: composercache
+#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+#
+#      - name: "Cache dependencies"
+#        uses: actions/cache@v2
+#        with:
+#          path: ${{ steps.composercache.outputs.dir }}
+#          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
+#          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
+#
+#      - name: "Install dependencies"
+#        run: "composer update --no-interaction --no-progress"
+#
+#      - name: "Lint XMLs"
+#        uses: ./.github/lint-xml-configuration
+#        with:
+#          args: bash .github/lint-xml-configuration/lint-xml-configuration.sh
 
   tests:
     name: "Tests"
@@ -105,13 +105,13 @@ jobs:
       matrix:
         os:
           - "ubuntu-latest"
-          - "windows-latest"
+#          - "windows-latest"
         php-version:
-          - "7.3"
-          - "7.4"
+#          - "7.3"
+#          - "7.4"
           - "8.0"
         dependencies:
-          - "lowest"
+#          - "lowest"
           - "highest"
 
     steps:
@@ -159,141 +159,141 @@ jobs:
 
       - name: "Run tests"
         timeout-minutes: 3
-        run: "vendor/bin/phpunit --no-coverage --no-logging"
+        run: "vendor/bin/phpunit --no-coverage --no-logging --filter testPrintFeedbackForMoreThan100Suites"
 
-  code-coverage:
-    name: "Code Coverage"
-
-    runs-on: "ubuntu-latest"
-
-    strategy:
-      matrix:
-        php-version:
-          - "7.4"
-
-    steps:
-      - name: "Checkout"
-        uses: "actions/checkout@v2"
-
-      - name: "Install PHP"
-        uses: "shivammathur/setup-php@v2"
-        with:
-          coverage: "pcov"
-          php-version: "${{ matrix.php-version }}"
-          ini-values: zend.assertions=1
-          tools: composer:v1
-
-      - name: "Get composer cache directory"
-        id: composercache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-
-      - name: "Cache dependencies"
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composercache.outputs.dir }}
-          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
-          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
-
-      - name: "Install dependencies"
-        run: "composer update --no-interaction --no-progress"
-
-      - name: "Run tests"
-        timeout-minutes: 3
-        run: "vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-xml=coverage/coverage-xml --log-junit=coverage/junit.xml"
-
-      - name: "Send code coverage report to Codecov.io"
-        uses: codecov/codecov-action@v1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          file: ./coverage.xml
-          fail_ci_if_error: true
-
-      - name: "Infection"
-        timeout-minutes: 10
-        run: "vendor/bin/infection --ansi --threads=$(nproc) --coverage=coverage --skip-initial-tests"
-        env:
-          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
-
-      - name: "Output infections"
-        run: "cat infections.log"
-
-  coding-standards:
-    name: "Coding Standards"
-
-    runs-on: "ubuntu-latest"
-
-    strategy:
-      matrix:
-        php-version:
-          - "7.3"
-
-    steps:
-      - name: "Checkout"
-        uses: "actions/checkout@v2"
-
-      - name: "Install PHP"
-        uses: "shivammathur/setup-php@v2"
-        with:
-          coverage: "none"
-          php-version: "${{ matrix.php-version }}"
-          tools: composer:v1, cs2pr
-
-      - name: "Get composer cache directory"
-        id: composercache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-
-      - name: "Cache dependencies"
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composercache.outputs.dir }}
-          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
-          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
-
-      - name: "Install dependencies"
-        run: "composer update --no-interaction --no-progress"
-
-      - name: "Check coding standards"
-        run: "vendor/bin/phpcs -q --report=checkstyle | cs2pr"
-
-  static-analysis:
-    name: "Static Analysis"
-
-    runs-on: "ubuntu-latest"
-
-    strategy:
-      matrix:
-        php-version:
-          - "7.4"
-
-    steps:
-      - name: "Checkout"
-        uses: "actions/checkout@v2"
-
-      - name: "Install PHP"
-        uses: "shivammathur/setup-php@v2"
-        with:
-          coverage: "none"
-          php-version: "${{ matrix.php-version }}"
-          tools: composer:v1, cs2pr
-
-      - name: "Get composer cache directory"
-        id: composercache
-        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
-
-      - name: "Cache dependencies"
-        uses: actions/cache@v2
-        with:
-          path: ${{ steps.composercache.outputs.dir }}
-          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
-          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
-
-      - name: "Install dependencies"
-        run: "composer update --no-interaction --no-progress"
-
-      - name: "Run static analysis"
-        run: "vendor/bin/phpstan analyse --no-progress --error-format=checkstyle | cs2pr"
-
-      - name: "Run PSalm for type-coverage"
-        run: |
-          vendor/bin/psalm --no-progress --show-info=false > /dev/null || true
-          vendor/bin/psalm --no-progress --shepherd --show-info=false --stats
+#  code-coverage:
+#    name: "Code Coverage"
+#
+#    runs-on: "ubuntu-latest"
+#
+#    strategy:
+#      matrix:
+#        php-version:
+#          - "7.4"
+#
+#    steps:
+#      - name: "Checkout"
+#        uses: "actions/checkout@v2"
+#
+#      - name: "Install PHP"
+#        uses: "shivammathur/setup-php@v2"
+#        with:
+#          coverage: "pcov"
+#          php-version: "${{ matrix.php-version }}"
+#          ini-values: zend.assertions=1
+#          tools: composer:v1
+#
+#      - name: "Get composer cache directory"
+#        id: composercache
+#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+#
+#      - name: "Cache dependencies"
+#        uses: actions/cache@v2
+#        with:
+#          path: ${{ steps.composercache.outputs.dir }}
+#          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
+#          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
+#
+#      - name: "Install dependencies"
+#        run: "composer update --no-interaction --no-progress"
+#
+#      - name: "Run tests"
+#        timeout-minutes: 3
+#        run: "vendor/bin/phpunit --coverage-clover=coverage.xml --coverage-xml=coverage/coverage-xml --log-junit=coverage/junit.xml"
+#
+#      - name: "Send code coverage report to Codecov.io"
+#        uses: codecov/codecov-action@v1
+#        with:
+#          token: ${{ secrets.CODECOV_TOKEN }}
+#          file: ./coverage.xml
+#          fail_ci_if_error: true
+#
+#      - name: "Infection"
+#        timeout-minutes: 10
+#        run: "vendor/bin/infection --ansi --threads=$(nproc) --coverage=coverage --skip-initial-tests"
+#        env:
+#          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
+#
+#      - name: "Output infections"
+#        run: "cat infections.log"
+#
+#  coding-standards:
+#    name: "Coding Standards"
+#
+#    runs-on: "ubuntu-latest"
+#
+#    strategy:
+#      matrix:
+#        php-version:
+#          - "7.3"
+#
+#    steps:
+#      - name: "Checkout"
+#        uses: "actions/checkout@v2"
+#
+#      - name: "Install PHP"
+#        uses: "shivammathur/setup-php@v2"
+#        with:
+#          coverage: "none"
+#          php-version: "${{ matrix.php-version }}"
+#          tools: composer:v1, cs2pr
+#
+#      - name: "Get composer cache directory"
+#        id: composercache
+#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+#
+#      - name: "Cache dependencies"
+#        uses: actions/cache@v2
+#        with:
+#          path: ${{ steps.composercache.outputs.dir }}
+#          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
+#          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
+#
+#      - name: "Install dependencies"
+#        run: "composer update --no-interaction --no-progress"
+#
+#      - name: "Check coding standards"
+#        run: "vendor/bin/phpcs -q --report=checkstyle | cs2pr"
+#
+#  static-analysis:
+#    name: "Static Analysis"
+#
+#    runs-on: "ubuntu-latest"
+#
+#    strategy:
+#      matrix:
+#        php-version:
+#          - "7.4"
+#
+#    steps:
+#      - name: "Checkout"
+#        uses: "actions/checkout@v2"
+#
+#      - name: "Install PHP"
+#        uses: "shivammathur/setup-php@v2"
+#        with:
+#          coverage: "none"
+#          php-version: "${{ matrix.php-version }}"
+#          tools: composer:v1, cs2pr
+#
+#      - name: "Get composer cache directory"
+#        id: composercache
+#        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+#
+#      - name: "Cache dependencies"
+#        uses: actions/cache@v2
+#        with:
+#          path: ${{ steps.composercache.outputs.dir }}
+#          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-${{ hashFiles('**/composer.json') }}
+#          restore-keys: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}-composer-
+#
+#      - name: "Install dependencies"
+#        run: "composer update --no-interaction --no-progress"
+#
+#      - name: "Run static analysis"
+#        run: "vendor/bin/phpstan analyse --no-progress --error-format=checkstyle | cs2pr"
+#
+#      - name: "Run PSalm for type-coverage"
+#        run: |
+#          vendor/bin/psalm --no-progress --show-info=false > /dev/null || true
+#          vendor/bin/psalm --no-progress --shepherd --show-info=false --stats
